apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: service-deploy
spec:
  resources:
    - name: appSource
      type: git
  tasks:
    - name: taskName
      taskRef:
        name: build-app
