apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: service-deploy
spec:
  resources:
    - name: appSource
      type: git
    - name: appImage
      type: image
  tasks:
    - name: build-app
      taskRef:
        name: build-app
      params:
        - name: contextDir
          value: springboot
      resources:
        inputs:
          - name: source
            resource: appSource
        outputs:
          - name: builtImage
            resource: appImage
    - name: kube-deploy
      taskRef:
        name: kubectl-deploy
      runAfter:
        - build-app
      resources:
        inputs:
          - name: source
            resource: appSource
      params:
        - name: contextDir
          value: springboot/k8s
